# fly.toml app configuration file generated for dancee-booking-backendd on 2025-09-27T10:18:52+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dancee-booking-backendd'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
