# fly.toml app configuration file generated for backend-late-river-4085 on 2025-09-26T22:59:09+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-late-river-4085'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
